#include "GameSimulation.h"
#include <iostream>

#include "game/ship/ShipInitData.h"
#include "game/ship/ShipRoleType.h"
#include "game/ship/ShipRegistry.h"
#include "game/ship/ShipVisualIdentity.h"
#include "game/ship/descriptors/EliteCobraMk1.h"

#include "game/items/cryptocard/CryptoCard.h"
#include "game/player/ActorCodeGenerator.h"
#include "src/game/player/ActorIdProvider.h"

#include "src/world/descriptors/ObjectDescriptorRegistry.h"
#include "src/game/geometry/ObjectAssemblyRegistry.h"
#include "src/world/types/ObjectType.h"


#include "game/equipment/radar/RadarModule.h"
// #include "src/world/modules/ObjectHitBuilder.h"
#include "src/game/geometry/AssemblyMeshLibrary.h"

#include "src/world/modules/ObjectRuntimeHitBuilder.h"
#include "src/world/modules/HitVolumeSnapshotBuilder.h"

#include <limits>
#include <glm/gtx/norm.hpp>
#include "src/world/modules/ObjectMissingPartRequest.h"

#include "game/promo/PromoFlybyScenario.h"
#include "game/scene/GameSceneSetup.h"

#include <glm/gtx/matrix_decompose.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtx/quaternion.hpp>

#include "src/world/coordinates/WorldPosition.h"

namespace
{
    game::simulation::ObjectModuleSnapshot buildModuleSnapshot(
        const ModuleDescriptor& descMod,
        const world::modules::ObjectModuleState* rt
    )
    {
        game::simulation::ObjectModuleSnapshot ms;

        ms.moduleId = descMod.moduleId;
        ms.parentModuleId = descMod.parentModuleId;
        ms.subsystemId = descMod.subsystemId;

        ms.maxHealth = descMod.maxHealth;
        ms.destructible = descMod.destructible;
        ms.detachable = descMod.detachable;
        ms.hangable = descMod.hangable;

        ms.destroyPolicy = static_cast<int>(descMod.destroyPolicy);
        ms.detachPolicy = static_cast<int>(descMod.detachPolicy);
        ms.attachmentType = static_cast<int>(descMod.attachmentType);

        ms.meshPartIds = descMod.meshPartIds;
        ms.supportModuleIds = descMod.supportModuleIds;
        ms.minSupportsForAttached = descMod.minSupportsForAttached;
        ms.minSupportsForStable = descMod.minSupportsForStable;

        if (rt)
        {
            ms.state = static_cast<uint8_t>(rt->state);
            ms.health = rt->health;
            ms.aliveSupportCount = rt->aliveSupportCount;
        }
        else
        {
            ms.state = 0;
            ms.health = descMod.maxHealth;
            ms.aliveSupportCount = 0;
        }

        return ms;
    }

    game::simulation::StructuralLinkSnapshot buildStructuralLinkSnapshot(
        const world::modules::StructuralLinkState& link
    )
    {
        game::simulation::StructuralLinkSnapshot ls;

        ls.id = link.id;
        ls.ownerModuleId = link.ownerModuleId;
        ls.moduleAId = link.moduleAId;
        ls.moduleBId = link.moduleBId;
        ls.kind = static_cast<int>(link.kind);

        ls.health = link.health;
        ls.maxHealth = link.maxHealth;
        ls.impulseTolerance = link.impulseTolerance;

        ls.loadBearing = link.loadBearing;
        ls.destroyed = link.destroyed;
        ls.autoGenerated = link.autoGenerated;

        ls.center = link.center;
        ls.halfSize = link.halfSize;
        ls.orientation = link.orientation;

        return ls;
    }
}

GameSimulation::GameSimulation()
{
    // ===================== ObjectDescriptor =========================

    ObjectDescriptorRegistry::init();
    game::ship::geometry::ObjectAssemblyRegistry::init();



    // ========================= PLAYER =========================

    // ShipVisualIdentity visualIdentity = {
    //     .shipType = "Cobra MK1",
    //     .shipName = "Jeraya"
    // };

    // ShipRegistry registry = {
    //     .instanceId      = 1,
    //     .ownerName       = "Jeraya",
    //     .ownerActor      = ActorIds::Player(),
    //     .registrationId  = "PL-0001",
    //     .homePort        = "Lave",
    //     .shipRole        = ShipRoleType::Civilian
    // };

    // auto* playerCard = new CryptoCard(
    //     generateActorCode(),
    //     "Player Access Card"
    // );
    // playerCard->actor = ActorIds::Player();

    // ShipInitData initData;
    // initData.visual = visualIdentity;
    // initData.registry = registry;
    // initData.initialInventory = {playerCard};

    // m_playerId = spawnShip(
    //     ShipRole::Player,
    //     EliteCobraMk1::EliteCobraMk1Descriptor(),
    //     {0.0f, 50.0f, 10.0f},
    //     initData
    // );

    // ========================= NPC #1 =========================

    // visualIdentity = {
    //     .shipType = "Cobra MK3",
    //     .shipName = "Scarlet Hawk Moth"
    // };

    // registry.instanceId = 2;

    // auto* npc1Card = new CryptoCard(
    //     generateActorCode(),
    //     "Player Access Card"
    // );
    // npc1Card->actor = ActorIds::Player();

    // initData.visual = visualIdentity;
    // initData.registry = registry;
    // initData.initialInventory = {npc1Card};

    // EntityId npcId1 = spawnShip(
    //     ShipRole::NPC,
    //     EliteCobraMk1::EliteCobraMk1Descriptor(),
    //     {20.0f, 0.0f, -50.0f},
    //     initData
    // );

    // // ========================= NPC #2 =========================

    // visualIdentity.shipName = "Hooded snake";
    // registry.instanceId = 3;

    // auto* npc2Card = new CryptoCard(
    //     generateActorCode(),
    //     "Player Access Card"
    // );
    // npc2Card->actor = ActorIds::Player();

    // initData.visual = visualIdentity;
    // initData.registry = registry;
    // initData.initialInventory = {npc2Card};

    // EntityId npcId2 =spawnShip(
    //     ShipRole::NPC,
    //     EliteCobraMk1::EliteCobraMk1Descriptor(),
    //     {-20.0f, 50.0f, -50.0f},
    //     initData
    // );


    // ================= Stantion Lexie Liu =========================
    //  spawnStation(ObjectType::Station, {0, 0, -1000});



    // ========================= INITIAL SCENE =========================

    m_playerId =
        game::scene::buildInitialScene(*this);



     if constexpr (game::promo::PromoFlybyScenario::Enabled)
    {
        m_promoFlybyScenario.setup(*this);
    }

}




//                       ###              ##
//                        ##              ##
//  ##  ##   ######       ##    ####     #####    ####
//  ##  ##    ##  ##   #####       ##     ##     ##  ##
//  ##  ##    ##  ##  ##  ##    #####     ##     ######
//  ##  ##    #####   ##  ##   ##  ##     ## ##  ##
//   ######   ##       ######   #####      ###    #####
//           ####

void GameSimulation::update(double dt)
{
    static float npcRepairThinkTimer = 0.0f;
    npcRepairThinkTimer += static_cast<float>(dt);

    const bool npcRepairThinkTick = npcRepairThinkTimer >= 15.0f;

    if (npcRepairThinkTick)
        npcRepairThinkTimer = 0.0f;

    
    static bool initialized = false;

    if (!initialized)
    {
        initialized = true;
    }

    // Режим 1: нормальная мощность
      
    float fdt = static_cast<float>(dt);
    m_serverTime += dt;


        for (auto& [id, ship] : m_ships)
    {
        if (!ship)
            continue;

        ship->core().updateAssemblyRuntime(dt);
        ship->core().updateDetachedFragments(fdt);
        ship->core().updateRepairJobs(fdt);


        if (npcRepairThinkTick &&
            ship->core().role() != ShipRole::Player &&
            ship->core().activeRepairJobCount() == 0)
        {
            const auto missing =
                ship->core().buildMissingPartRequests();

            if (!missing.empty())
            {
                // Пока тупо первая недостающая деталь.
                // Позже добавим приоритет: cockpit > engine > weapon > panel.
                startBestRepairJobForMissingSlot(
                    id,
                    missing.front().targetModuleId
                );
            }
        }

        auto& core = ship->core();
        if (core.hitVolumesDirty())
        {
            const auto& desc = core.descriptor();

            world::modules::ObjectRuntimeHitBuilder::rebuild(
                core.hitComponent(),
                desc.typeId,
                desc,
                core.moduleRuntime(),
                core.structuralLinkRuntime(),
                core.assemblyRuntime()
            );

            core.clearHitVolumesDirty();
        }
    }

    for (auto& [id, obj] : m_staticObjects)
    {
        // Вращение/анимация модулей НЕ требует полного rebuild hit-volumes.
        // Геометрия hit-volume уже посчитана в локальных координатах.
        // При движении/вращении должен меняться только transform, а не структура volume.
        obj.assemblyRuntime.update(dt);
        obj.detachedFragmentRuntime.update(fdt);

        if (obj.hitVolumesDirty)
        {
            const auto& desc = ObjectDescriptorRegistry::get(obj.type);

            world::modules::ObjectRuntimeHitBuilder::rebuild(
                obj.hitComponent,
                obj.type,
                desc,
                obj.moduleRuntime,
                obj.structuralLinkRuntime,
                obj.assemblyRuntime
            );

            obj.hitVolumesDirty = false;
            obj.staticSnapshotPayloadDirty = true;
        }
    }



    // === 1. AI phase ===
    for (auto& [id, shipPtr] : m_ships)
    {
        Ship& ship = *shipPtr;        
        if (id == m_playerId)
            continue;

        ShipControlState aiControl = m_npcAiSystem.computeControl(ship, fdt);
        ship.setControlState(aiControl);
    }

    for (auto& [id, shipPtr] : m_ships)
    {
        Ship& ship = *shipPtr;
        ship.applyControl();
    }

    for (auto& [id, shipPtr] : m_ships)
    {
        Ship& ship = *shipPtr;
        ship.updatePhysics(fdt, m_world);
    }

    // if constexpr (game::scene::GameSceneSetupConfig::PromoScene)
    // {
    //     updatePromoPlayerTracking(fdt);
    // }






    if constexpr (game::promo::PromoFlybyScenario::Enabled)
    {
        m_promoFlybyScenario.update(*this, fdt);
    }





    std::vector<ITransmitterSource*> signalSources;
    for (auto& [id, shipPtr] : m_ships)
    signalSources.push_back(shipPtr.get());

    WorldSignalTxSystem::collectFromSources(signalSources, m_worldSignals);

    for (auto& [id, shipPtr] : m_ships)
    {
        Ship& ship = *shipPtr;
        ship.updateSignals(fdt, m_worldSignals, m_planets, m_interferenceSources);
    }

    for (auto& [id, shipPtr] : m_ships)
    {
        Ship& ship = *shipPtr;

        std::vector<world::RadarContactInput> inputs;

        for (auto& [otherId, otherPtr] : m_ships)
        {
            if (id == otherId)
                continue;

            Ship& other = *otherPtr;

            const auto& otherTransform = other.core().transform();

            inputs.push_back({
                otherId,
                otherTransform.worldPosition,
                other.core().desc().radarCrossSection
            });
        }



        ship.updatePerception(fdt, inputs);
    }


    m_snapshot.serverTime = m_serverTime;
    m_snapshot.ships.clear();
    m_snapshot.objects.clear();
    m_snapshot.signals = m_worldSignals;


    // ----- тут собираем snapshot для кораблей ----------

    for (auto& [id, shipPtr] : m_ships)
    {
        Ship& ship = *shipPtr;
        ShipSnapshot s;

        const auto& tr = ship.core().transform();

        s.id = id;
        s.typeId = ship.core().desc().typeId;
        s.role = ship.core().role();

        s.transform = tr;


 
        s.receptions = ship.core().signalResults();
        

        s.radarContacts = ship.core().radar().getContacts();
        s.shipCoreStatus = ship.core().getCoreStatus();

        // s.modules.clear();
        // for (const auto& mod : ship.core().moduleRuntime().modules())
        // {
        //     game::simulation::ObjectModuleSnapshot ms;
        //     ms.moduleId = mod.moduleId;
        //     ms.state = static_cast<uint8_t>(mod.state);
        //     ms.health = mod.health;
        //     s.modules.push_back(std::move(ms));
        // }

                
        auto& graph = s.graph;

        auto resendIt = m_shipGraphPayloadFramesRemaining.find(id);
        const bool sendStructuralGraph =
            m_initializedShipGraphIds.find(id) == m_initializedShipGraphIds.end() ||
            resendIt != m_shipGraphPayloadFramesRemaining.end();

        if (sendStructuralGraph)
        {
            graph.hasModules = true;
            graph.hasStructuralLinks = true;
            graph.hasAssemblyModules = true;
            graph.hasDebugHitVolumes = true;

            const auto& runtimeModules = ship.core().moduleRuntime().modules();
            const auto& descModules = ship.core().desc().moduleDescriptors();

            std::unordered_map<std::string, const world::modules::ObjectModuleState*> runtimeById;
            runtimeById.reserve(runtimeModules.size());
            for (const auto& mod : runtimeModules)
                runtimeById[mod.moduleId] = &mod;

            graph.modules.reserve(descModules.size());
            for (const auto& descMod : descModules)
            {
                const auto itRt = runtimeById.find(descMod.moduleId);
                const auto* rt = (itRt != runtimeById.end()) ? itRt->second : nullptr;
                graph.modules.push_back(buildModuleSnapshot(descMod, rt));
            }

            const auto& links = ship.core().structuralLinkRuntime().links();
            graph.structuralLinks.reserve(links.size());
            for (const auto& link : links)
                graph.structuralLinks.push_back(buildStructuralLinkSnapshot(link));

            graph.assemblyModules = ship.core().assemblyRuntime().buildSnapshots();

            graph.debugHitVolumes = world::modules::HitVolumeSnapshotBuilder::build(
                ship.core().hitComponent()
            );

            m_initializedShipGraphIds.insert(id);

            if (resendIt != m_shipGraphPayloadFramesRemaining.end())
            {
                --resendIt->second;
                if (resendIt->second <= 0)
                    m_shipGraphPayloadFramesRemaining.erase(resendIt);
            }

            ship.core().clearHitVolumesDirty();
        }
        else if (ship.core().hitVolumesDirty())
        {
            // Debug-only payload: hit volumes can change after rebuilds.
            // Do not resend modules/links just because debug geometry changed.
            graph.hasDebugHitVolumes = true;
            graph.debugHitVolumes = world::modules::HitVolumeSnapshotBuilder::build(
                ship.core().hitComponent()
            );
            ship.core().clearHitVolumesDirty();
        }

        auto detachedFragments =
            ship.core().detachedFragmentRuntime().buildSnapshots(
                ship.core().transform().worldPosition
            );


        const bool hadDetachedFragments =
            m_shipsWithDetachedFragmentPayload.find(id) != m_shipsWithDetachedFragmentPayload.end();

        if (!detachedFragments.empty() || hadDetachedFragments)
        {
            graph.hasDetachedFragments = true;
            graph.detachedFragments = std::move(detachedFragments);

            if (graph.detachedFragments.empty())
                m_shipsWithDetachedFragmentPayload.erase(id);
            else
                m_shipsWithDetachedFragmentPayload.insert(id);
        }

        auto repairJobs = ship.core().buildRepairJobSnapshots();
        const bool hadRepairJobs =
            m_shipsWithRepairJobPayload.find(id) != m_shipsWithRepairJobPayload.end();

        if (!repairJobs.empty() || hadRepairJobs)
        {
            graph.hasRepairJobs = true;
            graph.repairJobs = std::move(repairJobs);

            if (graph.repairJobs.empty())
                m_shipsWithRepairJobPayload.erase(id);
            else
                m_shipsWithRepairJobPayload.insert(id);
        }

        m_snapshot.ships.push_back(s);
    }


    // ----- тут собираем snapshot для объектов ----------

    for (auto& [id, obj] : m_staticObjects)
    {
        ObjectSnapshot o;

        o.id = id;
        o.type = obj.type;

        // Теперь obj.worldPosition — это настоящая double-позиция
        // (её нужно будет добавить в структуру StaticObjectData)
        // Истина — obj.worldPosition.
        // position оставляем только как legacy mirror.
        o.worldPosition = obj.worldPosition;
        o.setWorldPosition(obj.worldPosition);
        o.orientation = obj.orientation;

        // Вращение станции меняет только assemblyModules.
        // Тяжелые статические payload'ы не пересобираем и не шлем каждый fixed tick.
        bool sendStaticPayload = obj.staticSnapshotPayloadDirty;

        if (obj.staticSnapshotPayloadDirty)
        {
            obj.cachedModuleSnapshots.clear();

            const auto& objDesc = ObjectDescriptorRegistry::get(obj.type);
            const auto& runtimeModules = obj.moduleRuntime.modules();
            const auto& descModules = objDesc.moduleDescriptors();

            std::unordered_map<std::string, const world::modules::ObjectModuleState*> runtimeById;
            runtimeById.reserve(runtimeModules.size());
            for (const auto& mod : runtimeModules)
            {
                runtimeById[mod.moduleId] = &mod;
            }

            for (const auto& descMod : descModules)
            {
                game::simulation::ObjectModuleSnapshot ms;

                ms.moduleId = descMod.moduleId;
                ms.parentModuleId = descMod.parentModuleId;
                ms.subsystemId = descMod.subsystemId;

                ms.maxHealth = descMod.maxHealth;
                ms.destructible = descMod.destructible;
                ms.detachable = descMod.detachable;
                ms.hangable = descMod.hangable;

                ms.destroyPolicy = static_cast<int>(descMod.destroyPolicy);
                ms.detachPolicy = static_cast<int>(descMod.detachPolicy);
                ms.attachmentType = static_cast<int>(descMod.attachmentType);

                ms.meshPartIds = descMod.meshPartIds;
                ms.supportModuleIds = descMod.supportModuleIds;
                ms.minSupportsForAttached = descMod.minSupportsForAttached;
                ms.minSupportsForStable = descMod.minSupportsForStable;

                auto itRt = runtimeById.find(descMod.moduleId);
                if (itRt != runtimeById.end() && itRt->second)
                {
                    const auto* rt = itRt->second;
                    ms.state = static_cast<uint8_t>(rt->state);
                    ms.health = rt->health;
                    ms.aliveSupportCount = rt->aliveSupportCount;
                }
                else
                {
                    ms.state = 0;
                    ms.health = descMod.maxHealth;
                    ms.aliveSupportCount = 0;
                }

                obj.cachedModuleSnapshots.push_back(std::move(ms));
            }

            obj.cachedStructuralLinkSnapshots.clear();

            for (const auto& link : obj.structuralLinkRuntime.links())
            {
                game::simulation::StructuralLinkSnapshot ls;

                ls.id = link.id;
                ls.ownerModuleId = link.ownerModuleId;
                ls.moduleAId = link.moduleAId;
                ls.moduleBId = link.moduleBId;
                ls.kind = static_cast<int>(link.kind);

                ls.health = link.health;
                ls.maxHealth = link.maxHealth;
                ls.impulseTolerance = link.impulseTolerance;

                ls.loadBearing = link.loadBearing;
                ls.destroyed = link.destroyed;
                ls.autoGenerated = link.autoGenerated;

                ls.center = link.center;
                ls.halfSize = link.halfSize;
                ls.orientation = link.orientation;

                obj.cachedStructuralLinkSnapshots.push_back(std::move(ls));
            }

            obj.cachedDebugHitVolumeSnapshots =
                world::modules::HitVolumeSnapshotBuilder::build(obj.hitComponent);

            obj.staticSnapshotPayloadDirty = false;
        }

        auto& graph = o.graph;

        if (sendStaticPayload)
        {
            graph.hasModules = true;
            graph.hasStructuralLinks = true;
            graph.hasDebugHitVolumes = true;

            graph.modules = obj.cachedModuleSnapshots;
            graph.structuralLinks = obj.cachedStructuralLinkSnapshots;
            graph.debugHitVolumes = obj.cachedDebugHitVolumeSnapshots;
        }

        // Это единственная часть станции, которая реально меняется при вращении.
        graph.hasAssemblyModules = true;
        graph.hasDetachedFragments = true;

        graph.assemblyModules = obj.assemblyRuntime.buildSnapshots();
        graph.detachedFragments =
            obj.detachedFragmentRuntime.buildSnapshots(
                obj.worldPosition
            );

        m_snapshot.objects.push_back(o);
    }

}











void GameSimulation::markShipGraphDirty(EntityId id)
{
    // GameSimulation builds an internal snapshot every simulation tick,
    // while GameServer publishes only every m_snapshotInterval ticks.
    // Keep heavy graph payload alive for several frames so the published
    // snapshot cannot miss the dirty structural update.
    m_shipGraphPayloadFramesRemaining[id] = 6;
}


void GameSimulation::debugForceFullShipGraphPayload()
{
    // structure_debug.html needs a complete graph on demand,
    // but normal gameplay snapshots must stay sparse/lightweight.
    for (const auto& [id, ship] : m_ships)
    {
        if (!ship)
            continue;

        markShipGraphDirty(id);
    }
}


void GameSimulation::setTick(uint32_t tick)
{
    m_snapshot.snapshotTick = tick;
}



EntityId GameSimulation::generateEntityId()
{
    EntityId id;
    id.value = m_nextEntityId++;
    return id;
}



EntityId GameSimulation::spawnShip(
    ShipRole role,
    const ShipDescriptor& descriptor,
    glm::vec3 position,
    const ShipInitData& initData,
    const glm::mat4& orientation
)
{
    // Ship ship;
    auto ship = std::make_unique<Ship>();

    EntityId id = generateEntityId();
    ship->setId(id);

    // ship.init(role, descriptor, position, initData);
    ship->init(role, descriptor, position, initData, orientation);

    // m_ships[id] = std::move(ship);
    m_ships[id] = std::move(ship);
    markShipGraphDirty(id);

    return id;
}



EntityId GameSimulation::spawnStation(
    ObjectType type,
    const glm::vec3& position,
    const glm::mat4& orientation
)
{
    EntityId id = generateEntityId();

    auto& obj = m_staticObjects[id];

    obj.id = id;
    obj.type = type; // ← ключевое изменение
    obj.setWorldPositionMeters(glm::dvec3(position));
    obj.orientation = orientation;

    const auto& baseDesc = ObjectDescriptorRegistry::get(type);

    obj.moduleRuntime.init(baseDesc.moduleDescriptors());
    obj.structuralLinkRuntime.init(baseDesc.moduleDescriptors());
    obj.moduleRuntime.reevaluateStructuralStates(&obj.structuralLinkRuntime);   

    if (game::ship::geometry::AssemblyMeshLibrary::has(type))
    {
        const auto& assembly = game::ship::geometry::AssemblyMeshLibrary::get(type);
        obj.assemblyRuntime.init(assembly);
        obj.detachedFragmentRuntime.clear();
    }

    world::modules::ObjectRuntimeHitBuilder::rebuild(
        obj.hitComponent,
        type,
        baseDesc,
        obj.moduleRuntime,
        obj.structuralLinkRuntime,
        obj.assemblyRuntime
    );
    obj.hitVolumesDirty = false;
    obj.staticSnapshotPayloadDirty = true;

    return id;
}













void GameSimulation::applyControl(EntityId id, const ShipControlState& control)
{
    Ship* ship = getShip(id);
    if (!ship)
        return;

    ship->setControlState(control);
}




bool GameSimulation::debugSetShipStructuralLinkHealth(
    EntityId id,
    const std::string& linkId,
    float health,
    bool destroyed
)
{
    Ship* ship = getShip(id);
    if (!ship)
        return false;

    const bool changed = ship->core().debugSetStructuralLinkHealth(
        linkId,
        health,
        destroyed
    );
    if (changed)
        markShipGraphDirty(id);
    return changed;
}











WorldParams& GameSimulation::world()
{
    return m_world;
}

const std::vector<WorldSignal>& GameSimulation::worldSignals() const
{
    return m_worldSignals;
}

const std::vector<Planet>& GameSimulation::planets() const
{
    return m_planets;
}

const std::vector<InterferenceSource>& GameSimulation::interferenceSources() const
{
    return m_interferenceSources;
}

Ship* GameSimulation::getShip(EntityId id)
{
    auto it = m_ships.find(id);
    if (it == m_ships.end())
        return nullptr;
    return it->second.get();
}

const Ship* GameSimulation::getShip(EntityId id) const
{
    auto it = m_ships.find(id);
    if (it == m_ships.end())
        return nullptr;
    return it->second.get();
}

Ship* GameSimulation::playerShip()
{
    return getShip(m_playerId);
}

const Ship* GameSimulation::playerShip() const
{
    return getShip(m_playerId);
}


bool GameSimulation::debugDestroyShipModule(EntityId id, const std::string& moduleId)
{
    Ship* ship = getShip(id);
    if (!ship)
    {
        std::cout
            << "[GameSimulation] debugDestroyShipModule: ship not found, entityId="
            << id.value << "\n";
        return false;
    }

    const bool changed = ship->core().debugDestroyModuleById(moduleId);
    if (changed)
        markShipGraphDirty(id);
    return changed;
}


bool GameSimulation::debugDetachShipModule(EntityId id, const std::string& moduleId)
{
    Ship* ship = getShip(id);
    if (!ship)
        return false;

    const bool changed = ship->core().debugDetachModuleById(moduleId);
    if (changed)
        markShipGraphDirty(id);
    return changed;
}



bool GameSimulation::debugReattachShipModule(
    EntityId id,
    const std::string& moduleId
)
{
    Ship* ship = getShip(id);
    if (!ship)
        return false;

    const bool changed = ship->core().debugReattachModuleById(moduleId);
    if (changed)
        markShipGraphDirty(id);
    return changed;
}




bool GameSimulation::startShipRepairJob(
    EntityId id,
    const std::string& moduleId
)
{
    Ship* ship = getShip(id);
    if (!ship)
        return false;

    const bool changed = ship->core().startRepairJobForModule(moduleId);
    if (changed)
        markShipGraphDirty(id);
    return changed;
}




bool GameSimulation::ejectShipCockpitCapsule(EntityId id)
{
    Ship* ship = getShip(id);
    if (!ship)
    {
        std::cout
            << "[GameSimulation] ejectShipCockpitCapsule: ship not found, entityId="
            << id.value << "\n";
        return false;
    }

    const bool changed = ship->core().ejectCockpitCapsule();
    if (changed)
        markShipGraphDirty(id);
    return changed;
}






bool GameSimulation::debugHangShipModule(EntityId id, const std::string& moduleId)
{
    Ship* ship = getShip(id);
    if (!ship)
        return false;

    const bool changed = ship->core().debugHangModuleById(moduleId);
    if (changed)
        markShipGraphDirty(id);
    return changed;
}

bool GameSimulation::debugReevaluateShipStructure(EntityId id)
{
    Ship* ship = getShip(id);
    if (!ship)
        return false;

    const bool changed = ship->core().debugReevaluateStructure();
    if (changed)
        markShipGraphDirty(id);
    return changed;
}


bool GameSimulation::debugRestoreShipModule(EntityId id, const std::string& moduleId)
{
    Ship* ship = getShip(id);
    if (!ship)
    {
        std::cout
            << "[GameSimulation] debugRestoreShipModule: ship not found, entityId="
            << id.value << "\n";
        return false;
    }

    const bool changed = ship->core().debugRestoreModuleById(moduleId);
    if (changed)
        markShipGraphDirty(id);
    return changed;
}

bool GameSimulation::debugResetShipStructure(EntityId id)
{
    Ship* ship = getShip(id);
    if (!ship)
    {
        std::cout
            << "[GameSimulation] debugResetShipStructure: ship not found, entityId="
            << id.value << "\n";
        return false;
    }

    const bool changed = ship->core().debugResetStructure();
    if (changed)
        markShipGraphDirty(id);
    return changed;
}

void GameSimulation::debugResetAllShipStructures()
{
    for (auto& [id, ship] : m_ships)
    {
        if (ship)
        {
            const bool changed = ship->core().debugResetStructure();
            if (changed)
                markShipGraphDirty(id);
        }
    }

    std::cout << "[GameSimulation] debugResetAllShipStructures\n";
}


void GameSimulation::setPlayerControl(const ShipControlState& control)
{
    m_playerControlState = control;
}

const SimulationSnapshot& GameSimulation::snapshot() const
{
    return m_snapshot;
}

std::unordered_map<EntityId, std::unique_ptr<Ship>>& GameSimulation::ships()
{
    return m_ships;
}


bool GameSimulation::startBestRepairJobForMissingSlot(
    EntityId targetShipId,
    const std::string& targetModuleId
)
{
    Ship* targetShip = getShip(targetShipId);
    if (!targetShip)
        return false;

    const auto requests =
        targetShip->core().buildMissingPartRequests();

    const world::modules::ObjectMissingPartRequest* targetRequest = nullptr;

    for (const auto& req : requests)
    {
        if (req.targetModuleId == targetModuleId)
        {
            targetRequest = &req;
            break;
        }
    }

    if (!targetRequest)
    {
        std::cout
            << "[GameSimulation] no missing slot targetModuleId="
            << targetModuleId << "\n";
        return false;
    }

    Ship* bestSourceShip = nullptr;
    std::string bestSourceModuleId;
    float bestDistance2 = std::numeric_limits<float>::max();

    for (auto& [sourceId, sourceShipPtr] : m_ships)
    {
        if (!sourceShipPtr)
            continue;

        Ship* sourceShip = sourceShipPtr.get();

        for (const auto& fragment :
             sourceShip->core().detachedFragmentRuntime().fragments())
        {
            if (!fragment.salvageable && !fragment.repairable)
                continue;

            if (fragment.moduleClass != targetRequest->moduleClass)
                continue;

            if (!world::modules::replacementTagsCompatible(
                    targetRequest->acceptedReplacementTags,
                    fragment.providedReplacementTags))
            {
                continue;
            }

            const world::coordinates::WorldPosition fragmentWorldPosition =
                world::coordinates::translated(
                    sourceShip->core().transform().worldPosition,
                    glm::dvec3(fragment.position)
                );

            const float dist2 =
                targetShip->core().transform().distanceSquaredToWorldPosition(
                    fragmentWorldPosition
                );

            if (dist2 < bestDistance2)
            {
                bestDistance2 = dist2;
                bestSourceShip = sourceShip;
                bestSourceModuleId = fragment.moduleId;
            }
        }
    }

    if (!bestSourceShip)
    {
        std::cout
            << "[GameSimulation] no compatible detached part for targetModuleId="
            << targetModuleId
            << " moduleClass="
            << targetRequest->moduleClass
            << "\n";
        return false;
    }

    std::cout
        << "[GameSimulation] repair missing slot:"
        << " targetShipId=" << targetShipId.value
        << " targetModuleId=" << targetModuleId
        << " sourceModuleId=" << bestSourceModuleId
        << "\n";

    return targetShip->core().startRepairJobForClaimedReplacement(
        targetModuleId,
        bestSourceShip->core().detachedFragmentRuntime(),
        bestSourceModuleId
    );
}




bool GameSimulation::startBestRepairJobForFirstMissingSlot(EntityId targetShipId)
{
    Ship* targetShip = getShip(targetShipId);
    if (!targetShip)
        return false;

    const auto missing =
        targetShip->core().buildMissingPartRequests();

    if (missing.empty())
    {
        std::cout
            << "[GameSimulation] no missing slots for shipId="
            << targetShipId.value << "\n";
        return false;
    }

    for (const auto& req : missing)
    {
        if (startBestRepairJobForMissingSlot(
                targetShipId,
                req.targetModuleId))
        {
            std::cout
                << "[GameSimulation] started repair for first available missing slot moduleId="
                << req.targetModuleId << "\n";
            return true;
        }
    }

    std::cout
        << "[GameSimulation] no compatible parts for any missing slot shipId="
        << targetShipId.value << "\n";

    return false;
}







glm::vec3 GameSimulation::promoWingCenterAtTime(float time) const
{
    const glm::vec3 playerPos {0.0f, 50.0f, 0.0f};
    const glm::vec3 flightDir {0.0f, 0.0f, -1.0f};

    const float wingSpeed = 120.0f;
    const float passHeight = 260.0f;
    const float spawnDistance = 1800.0f;

    const float forwardDist =
        -spawnDistance + wingSpeed * time;

    glm::vec3 center =
        playerPos + flightDir * forwardDist;

    center.y =
        playerPos.y + passHeight;

    // ВАЖНО:
    // Пока звено не пролетело игрока, НЕ учитываем разделение.
    // Иначе нос игрока начинает заранее уходить за будущей траекторией.
    const float splitStart =
        260.0f;

    float splitT =
        (forwardDist - splitStart) / 900.0f;

    splitT =
        std::clamp(splitT, 0.0f, 1.0f);

    splitT =
        splitT * splitT * splitT *
        (splitT * (splitT * 6.0f - 15.0f) + 10.0f);

    center += glm::vec3(
        0.0f,
        360.0f,
        -360.0f
    ) * splitT;

    return center;
}









glm::mat4 GameSimulation::makePromoLookOrientation(
    const glm::vec3& forward,
    const glm::vec3& upHint
) const
{
    glm::vec3 f = forward;

    if (glm::length2(f) < 0.000001f)
        f = glm::vec3(0.0f, 0.0f, -1.0f);

    f = glm::normalize(f);

    glm::vec3 r =
        glm::cross(f, upHint);

    if (glm::length2(r) < 0.000001f)
        r = glm::cross(f, glm::vec3(0.0f, 0.0f, 1.0f));

    r = glm::normalize(r);

    glm::vec3 u =
        glm::normalize(glm::cross(r, f));

    glm::mat4 m(1.0f);

    // Engine convention:
    // +X right, +Y up, -Z forward
    m[0] = glm::vec4(r, 0.0f);
    m[1] = glm::vec4(u, 0.0f);
    m[2] = glm::vec4(-f, 0.0f);
    m[3] = glm::vec4(0, 0, 0, 1);

    return m;
}

void GameSimulation::updatePromoPlayerTracking(float dt)
{
   

    auto it =
        m_ships.find(m_playerId);

    if (it == m_ships.end() || !it->second)
        return;

    Ship& playerShip =
        *it->second;

    auto& tr =
        playerShip.core().transform();

    auto& control =
        playerShip.core().control();

    // Фиксируем игрока как операторскую платформу.
    const glm::vec3 playerPos {0.0f, 50.0f, 0.0f};

    tr.setWorldPositionMeters(glm::dvec3(playerPos));
    tr.forwardVelocity = 0.0f;
    tr.targetSpeed = 0.0f;
    tr.localVelocity = glm::vec3(0.0f);

    tr.pitchRate = 0.0f;
    tr.yawRate = 0.0f;
    tr.rollRate = 0.0f;

    control.forwardInput = 0.0f;
    control.strafeInput = 0.0f;
    control.liftInput = 0.0f;

    control.pitchInput = 0.0f;
    control.yawInput = 0.0f;
    control.rollInput = 0.0f;

    control.cruiseActive = false;
    control.jumpActive = false;
    control.targetSpeedRate = 0.0f;

    const float localTime =
        std::fmod(
            static_cast<float>(m_serverTime),
            22.0f
        );

    const glm::vec3 target =
        promoWingCenterAtTime(localTime);

    const world::coordinates::WorldPosition targetWorldPosition =
        world::coordinates::makeWorldPositionFromMeters(
            glm::dvec3(target)
        );

    glm::vec3 forward =
        tr.worldPositionToLocalCell(targetWorldPosition);

    if (glm::length2(forward) < 0.000001f)
        forward = glm::vec3(0.0f, 0.0f, -1.0f);

    forward =
        glm::normalize(forward);

    // Когда звено проходит над кораблём, делаем roll 180°,
    // чтобы звено оставалось в верхней части кадра.
    //
    // forwardDist совпадает с promoWingCenterAtTime().
    const float wingSpeed = 120.0f;
    const float spawnDistance = 1800.0f;

    const float forwardDist =
        -spawnDistance + wingSpeed * localTime;

    float rollT =
    (forwardDist - 40.0f) / 520.0f;

    rollT =
        std::clamp(rollT, 0.0f, 1.0f);

    rollT =
        rollT * rollT * rollT *
        (rollT * (rollT * 6.0f - 15.0f) + 10.0f);

    glm::vec3 upHint =
        glm::mix(
            glm::vec3(0.0f, 1.0f, 0.0f),
            glm::vec3(0.0f, -1.0f, 0.0f),
            rollT
        );

    glm::mat4 targetOrientation =
        makePromoLookOrientation(
            forward,
            upHint
        );

    glm::quat currentQ =
        glm::quat_cast(tr.orientation);

    glm::quat targetQ =
        glm::quat_cast(targetOrientation);

    // Никаких резких поворотов.
    const float turnResponse = 1.15f;

    const float blend =
        1.0f - std::exp(-turnResponse * dt);

    glm::quat q =
        glm::slerp(
            currentQ,
            targetQ,
            blend
        );

    tr.orientation =
        glm::toMat4(glm::normalize(q));
}