#pragma once

#include <cstddef>
#include <cstdint>
#include <limits>
#include <string>
#include <vector>

#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>

#include "src/world/navigation/NavigationObstacle.h"
#include "src/world/navigation/NavigationVehicleProfile.h"
#include "src/world/navigation/Trajectory.h"

namespace world::navigation
{

/*
    Spatial manual-flight guide sampled at equal arc-length intervals.

    The tunnel is deliberately separate from HUD rendering. Each gate is a
    desired vehicle pose in the trajectory's planning frame. The initial route
    product is sampled directly; a live-pose reconnect, when required, is solved
    through the canonical Ruckig state-to-state backend and collision checked
    against the same navigation geometry as route planning.
*/
struct GuidanceTunnelGate
{
    double distanceAlongTunnelMeters = 0.0;
    double sourceTrajectoryProgressMeters = 0.0;

    glm::dvec3 positionMeters {0.0};
    glm::dquat orientation {1.0, 0.0, 0.0, 0.0};

    double widthMeters = 0.0;
    double heightMeters = 0.0;
    double lateralToleranceMeters = 0.0;
    double verticalToleranceMeters = 0.0;
    double recommendedSpeedMps = 0.0;
};

struct GuidanceTunnel
{
    bool valid = false;
    int systemId = -1;
    std::string frameId;
    std::vector<GuidanceTunnelGate> gates;

    // Progress on the immutable accepted trajectory already behind the live
    // vehicle when a reconnect generation was built.
    double passedTrajectoryProgressMeters = 0.0;
    double maxCurvaturePerMeter = 0.0;
    double minimumTurnRadiusMeters = 0.0;

    // Rolling reconnect diagnostics. In bounded mode Ruckig replaces only the
    // current-pose -> accepted-trajectory rejoin and the accepted tail is kept.
    // Full fallback is reserved for moved terminals or an infeasible local join.
    bool reconnectSolveBounded = false;
    bool reconnectFullSolveFallback = false;
    double reconnectSolveStartProgressMeters = 0.0;
    double reconnectSolveEndProgressMeters = 0.0;
    double reconnectLookaheadMeters = 0.0;
};

enum class GuidanceTunnelBuildMode
{
    // Presentation-only sampling of the already accepted collision-safe
    // trajectory. No second geometric/trajectory solve is performed.
    TrajectoryBackbone,

    // Explicit live-pose correction. The local replacement is generated by
    // Ruckig and swept against canonical navigation obstacles before publish.
    ReconnectCurrentPose
};

struct GuidanceTunnelRequest
{
    const Trajectory* trajectory = nullptr;
    GuidanceTunnelBuildMode buildMode =
        GuidanceTunnelBuildMode::ReconnectCurrentPose;

    glm::dvec3 currentPositionMeters {0.0};
    glm::dquat currentOrientation {1.0, 0.0, 0.0, 0.0};
    // Geometry follows actual motion when available. Hull attitude remains the
    // roll/up reference for the guidance-frame orientation field.
    glm::dvec3 currentVelocityMps {0.0};

    glm::dvec3 terminalPositionMeters {0.0};
    glm::dquat terminalOrientation {1.0, 0.0, 0.0, 0.0};

    // Gates are equidistant by actual tunnel arc length. The final gate is
    // always emitted even when the final remainder is shorter than this value.
    double gateSpacingMeters = 25.0;

    double gateWidthMeters = 0.0;
    double gateHeightMeters = 0.0;
    double lateralToleranceMeters = 0.0;
    double verticalToleranceMeters = 0.0;

    double startCaptureDistanceMeters = 250.0;
    double terminalAlignmentDistanceMeters = 350.0;

    // Ruckig reconnect legs are accepted only after exact swept checks against
    // these canonical navigation obstacles. The target obstacle may be entered
    // only after the authored ingress progress below.
    std::vector<NavigationObstacle> obstacles;
    NavigationVehicleProfile vehicle;
    std::string terminalAllowedObstacleId;
    double terminalObstacleEntrySourceProgressMeters =
        std::numeric_limits<double>::infinity();

    // Legacy spline-era request knobs retained temporarily for source/API
    // compatibility. The Ruckig reconnect backend intentionally ignores them.
    double curveSampleSpacingMeters = 6.0;
    double curveChordErrorMeters = 0.05;
    std::size_t maxSmoothSupportLevel = 4;

    // Used only to extend the physical reconnect horizon before an imminent
    // course change. Ruckig itself enforces acceleration/jerk state limits.
    double minimumTurnRadiusMeters = 0.0;

    // The bounded reconnect horizon is at least
    //
    //   v*T_latency + v^2/(2*a_brake) + turn_distance + safety_margin
    //
    // measured along the immutable accepted trajectory.
    double reconnectPlanningLatencySeconds = 0.75;
    double reconnectSafetyMarginMeters = 0.0; // 0 => automatic conservative margin

    // If the live terminal moved materially relative to the accepted product,
    // the bounded immutable-tail shortcut is not legal; a full Ruckig reconnect
    // is attempted instead and still must pass collision validation.
    double reconnectMaxTerminalPositionDriftMeters = 2.0;
    double reconnectMaxTerminalAngleDriftRadians = 0.008726646259971648; // 0.5 deg
};

class GuidanceTunnelBuilder
{
public:
    static GuidanceTunnel build(const GuidanceTunnelRequest& request);
};

} // namespace world::navigation
