#pragma once

#include <string>
#include <vector>

#include "src/world/modules/StructuralLinkState.h"
#include "src/world/descriptors/ModuleDescriptor.h"

namespace world::modules
{

class ObjectStructuralLinkRuntime
{
public:
    void init(const std::vector<ModuleDescriptor>& descriptors);

    void clear();
    void clearAutoGenerated(StructuralLinkKind kind);

    void add(const StructuralLinkState& link);
    void addOrReplaceAutoGenerated(const StructuralLinkState& link);

    StructuralLinkState* findById(const std::string& id);
    const StructuralLinkState* findById(const std::string& id) const;

    bool setLinkHealth(
        const std::string& linkId,
        float health,
        bool destroyed
    );

    const std::vector<StructuralLinkState>& links() const { return m_links; }
    std::vector<StructuralLinkState>& links() { return m_links; }

    int restoreLinksTouchingModule(const std::string& moduleId);

private:
    StructuralLinkKind inferKind(const ModuleDescriptor& desc) const;

private:
    std::vector<StructuralLinkState> m_links;
};

} // namespace world::modules