#pragma once

#include <string>
#include <glm/glm.hpp>

namespace world::modules
{

enum class StructuralLinkKind
{
    PanelSeam = 0,
    FrameMount,
    HardMount,
    EquipmentBracket
};

struct StructuralLinkState
{
    std::string id;

    // Временный "владелец" для совместимости с текущей логикой поддержки модуля.
    // На этом этапе link уже самостоятельная сущность,
    // но module runtime всё ещё считает attached/hanging через ownerModuleId.
    std::string ownerModuleId;

    // Честные концы связи
    std::string moduleAId;
    std::string moduleBId;

    StructuralLinkKind kind = StructuralLinkKind::PanelSeam;

    float maxHealth = 100.0f;
    float health = 100.0f;
    float impulseTolerance = 250.0f;

    bool loadBearing = true;
    bool destroyed = false;
    bool autoGenerated = false;

    // Геометрия link-volume
    glm::vec3 center {0.0f};
    glm::vec3 halfSize {0.05f, 0.05f, 0.05f};
    glm::mat3 orientation {1.0f};

    bool isAlive() const
    {
        return !destroyed && health > 0.0f;
    }
};

} // namespace world::modules