#include "ObjectStructuralLinkRuntime.h"

#include <algorithm>

namespace world::modules
{

StructuralLinkKind ObjectStructuralLinkRuntime::inferKind(const ModuleDescriptor& desc) const
{
    if (desc.structuralKind == ModuleStructuralKind::OuterPanel)
        return StructuralLinkKind::PanelSeam;

    if (desc.structuralKind == ModuleStructuralKind::StructuralFrame)
        return StructuralLinkKind::FrameMount;

    if (desc.attachmentType == ModuleAttachmentType::Hardpoint)
        return StructuralLinkKind::HardMount;

    return StructuralLinkKind::EquipmentBracket;
}

void ObjectStructuralLinkRuntime::init(const std::vector<ModuleDescriptor>& descriptors)
{
    m_links.clear();

    for (const auto& desc : descriptors)
    {
        if (!desc.supportLinks.empty())
        {
            for (const auto& linkDesc : desc.supportLinks)
            {
                StructuralLinkState link;
                link.id = linkDesc.linkId;
                link.ownerModuleId = desc.moduleId;
                link.moduleAId = desc.moduleId;
                link.moduleBId = linkDesc.supportModuleId;
                link.kind = inferKind(desc);

                link.maxHealth = linkDesc.maxHealth;
                link.health = linkDesc.maxHealth;
                link.impulseTolerance = linkDesc.impulseTolerance;
                link.loadBearing = linkDesc.loadBearing;
                link.destroyed = false;
                link.autoGenerated = false;

                m_links.push_back(std::move(link));
            }
        }
        else
        {
            for (const auto& supportId : desc.supportModuleIds)
            {
                StructuralLinkState link;
                link.id = desc.moduleId + "::support::" + supportId;
                link.ownerModuleId = desc.moduleId;
                link.moduleAId = desc.moduleId;
                link.moduleBId = supportId;
                link.kind = inferKind(desc);

                link.maxHealth = desc.autoSupportLinkHealth;
                link.health = desc.autoSupportLinkHealth;
                link.impulseTolerance = desc.autoSupportImpulseTolerance;
                link.loadBearing = true;
                link.destroyed = false;
                link.autoGenerated = false;

                m_links.push_back(std::move(link));
            }
        }
    }
}

void ObjectStructuralLinkRuntime::clear()
{
    m_links.clear();
}

void ObjectStructuralLinkRuntime::clearAutoGenerated(StructuralLinkKind kind)
{
    m_links.erase(
        std::remove_if(
            m_links.begin(),
            m_links.end(),
            [kind](const StructuralLinkState& link)
            {
                return link.autoGenerated && link.kind == kind;
            }
        ),
        m_links.end()
    );
}

void ObjectStructuralLinkRuntime::add(const StructuralLinkState& link)
{
    m_links.push_back(link);
}

void ObjectStructuralLinkRuntime::addOrReplaceAutoGenerated(const StructuralLinkState& link)
{
    for (auto& existing : m_links)
    {
        if (existing.id == link.id)
        {
            existing = link;
            return;
        }
    }

    m_links.push_back(link);
}

StructuralLinkState* ObjectStructuralLinkRuntime::findById(const std::string& id)
{
    for (auto& link : m_links)
    {
        if (link.id == id)
            return &link;
    }

    return nullptr;
}

const StructuralLinkState* ObjectStructuralLinkRuntime::findById(const std::string& id) const
{
    for (const auto& link : m_links)
    {
        if (link.id == id)
            return &link;
    }

    return nullptr;
}

bool ObjectStructuralLinkRuntime::setLinkHealth(
    const std::string& linkId,
    float health,
    bool destroyed
)
{
    auto* link = findById(linkId);
    if (!link)
        return false;

    link->health = health;
    if (link->health < 0.0f)
        link->health = 0.0f;

    link->destroyed = destroyed || link->health <= 0.0f;
    return true;
}


int ObjectStructuralLinkRuntime::restoreLinksTouchingModule(
    const std::string& moduleId
)
{
    int restored = 0;

    for (auto& link : m_links)
    {
        if (link.moduleAId != moduleId && link.moduleBId != moduleId)
            continue;

        link.health = link.maxHealth;
        link.destroyed = false;

        ++restored;
    }

    return restored;
}

} // namespace world::modules