#pragma once

#include <string>
#include <glm/glm.hpp>

namespace game::simulation
{

struct StructuralLinkSnapshot
{
    std::string id;

    std::string ownerModuleId;
    std::string moduleAId;
    std::string moduleBId;

    int kind = 0;

    float health = 0.0f;
    float maxHealth = 0.0f;
    float impulseTolerance = 0.0f;

    bool loadBearing = true;
    bool destroyed = false;
    bool autoGenerated = false;

    glm::vec3 center {0.0f};
    glm::vec3 halfSize {0.05f};
    glm::mat3 orientation {1.0f};
};

}